# Generated by Django 4.1 on 2024-05-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basevalue",
            old_name="base",
            new_name="base_value",
        ),
        migrations.AddField(
            model_name="log",
            name="is_done",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rule",
            name="punishment",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="rule",
            name="reward",
            field=models.FloatField(default=0.0),
        ),
    ]
